"""schema initial

Revision ID: f3aad55f1bb3
Revises: 
Create Date: 2026-08-01 22:43:23.483790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3aad55f1bb3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domaines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('libelle')
    )
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=100), nullable=False),
    sa.Column('date_publication', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=200), nullable=True),
    sa.Column('type_publication', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_blacklist_jti'), 'refresh_token_blacklist', ['jti'], unique=True)
    op.create_table('secteurs_activite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('types_procedure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('libelle')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('repnom', sa.String(length=255), nullable=True),
    sa.Column('repprenom', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('notifications_actives', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('activation_token', sa.UUID(), nullable=False),
    sa.Column('activation_token_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active_entreprise_id', sa.Integer(), nullable=True),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_table('entreprises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('numero_identification', sa.String(length=100), nullable=False),
    sa.Column('siret', sa.String(length=20), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repnom', sa.String(length=255), nullable=True),
    sa.Column('repprenom', sa.String(length=255), nullable=True),
    sa.Column('rccm', sa.String(length=15), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['utilisateurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_identification'),
    sa.UniqueConstraint('siret')
    )
    # Contrainte circulaire (utilisateurs.active_entreprise_id -> entreprises.id) ajoutee via
    # ALTER TABLE une fois les deux tables creees : op.create_table ne sait pas emettre une FK
    # "use_alter" toute seule (le flag est ignore si on le laisse dans la liste de contraintes du
    # create_table, la contrainte ne serait alors jamais reellement creee - constate en reel).
    op.create_foreign_key(
        'fk_utilisateurs_active_entreprise', 'utilisateurs', 'entreprises',
        ['active_entreprise_id'], ['id'], ondelete='SET NULL',
    )
    op.create_table('marches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('type_procedure_id', sa.Integer(), nullable=True),
    sa.Column('ministere', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('objet', sa.Text(), nullable=False),
    sa.Column('budget_min', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_procedure_id'], ['types_procedure.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publication_domaines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('domaine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domaine_id'], ['domaines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publication_id', 'domaine_id')
    )
    op.create_table('alertes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('type_alerte', sa.String(length=50), nullable=False),
    sa.Column('date_alerte', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contenu_alerte', sa.Text(), nullable=False),
    sa.Column('canal_alerte', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appels_offre',
    sa.Column('marche_id', sa.Integer(), nullable=False),
    sa.Column('dateDepot', sa.Date(), nullable=True),
    sa.Column('referenceDossier', sa.String(length=255), nullable=True),
    sa.Column('lieuDepot', sa.Text(), nullable=True),
    sa.Column('conditionsParticipation', sa.Text(), nullable=True),
    sa.Column('criteresSelection', sa.Text(), nullable=True),
    sa.Column('cautionnement', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('dureeValiditeOffres', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['marche_id'], ['marches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('marche_id')
    )
    op.create_table('entreprise_domaines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('domaine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domaine_id'], ['domaines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'domaine_id')
    )
    op.create_table('entreprise_secteurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.Column('secteur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['secteur_id'], ['secteurs_activite.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entreprise_id', 'secteur_id')
    )
    op.create_table('lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marche_id', sa.Integer(), nullable=False),
    sa.Column('numero_lot', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('montant', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['marche_id'], ['marches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultats',
    sa.Column('marche_id', sa.Integer(), nullable=False),
    sa.Column('date_attribution', sa.Date(), nullable=True),
    sa.Column('entreprise_attributaire_id', sa.Integer(), nullable=True),
    sa.Column('montant_attribue', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('reference_decision', sa.String(length=255), nullable=True),
    sa.Column('nombre_offres_recues', sa.Integer(), nullable=True),
    sa.Column('delai_execution', sa.String(length=255), nullable=True),
    sa.Column('motif_rejet_autres_offres', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_attributaire_id'], ['entreprises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['marche_id'], ['marches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('marche_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultats')
    op.drop_table('lots')
    op.drop_table('entreprise_secteurs')
    op.drop_table('entreprise_domaines')
    op.drop_table('appels_offre')
    op.drop_table('alertes')
    op.drop_table('publication_domaines')
    op.drop_table('marches')
    op.drop_constraint('fk_utilisateurs_active_entreprise', 'utilisateurs', type_='foreignkey')
    op.drop_table('entreprises')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_table('types_procedure')
    op.drop_table('secteurs_activite')
    op.drop_index(op.f('ix_refresh_token_blacklist_jti'), table_name='refresh_token_blacklist')
    op.drop_table('refresh_token_blacklist')
    op.drop_table('publications')
    op.drop_table('domaines')
    # ### end Alembic commands ###
