# Generated by Django 5.2.4 on 2025-07-11 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecteurActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('numero_identification', models.CharField(max_length=100, unique=True)),
                ('siret', models.CharField(max_length=20, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('repnom', models.CharField(blank=True, max_length=255, null=True)),
                ('repprenom', models.CharField(blank=True, max_length=255, null=True)),
                ('rccm', models.CharField(blank=True, max_length=15, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_entreprises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntrepriseDomaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.domaine')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise')),
            ],
            options={
                'unique_together': {('entreprise', 'domaine')},
            },
        ),
        migrations.AddField(
            model_name='entreprise',
            name='domaines',
            field=models.ManyToManyField(through='entreprise.EntrepriseDomaine', to='entreprise.domaine'),
        ),
        migrations.CreateModel(
            name='EntrepriseSecteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.secteuractivite')),
            ],
            options={
                'unique_together': {('entreprise', 'secteur')},
            },
        ),
        migrations.AddField(
            model_name='entreprise',
            name='secteurs',
            field=models.ManyToManyField(through='entreprise.EntrepriseSecteur', to='entreprise.secteuractivite'),
        ),
    ]
