# Generated by Django 5.2.5 on 2025-09-11 13:36

import backend.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministere', models.CharField(blank=True, max_length=255, null=True, verbose_name='ministère ou entité')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='région')),
                ('objet', models.TextField(verbose_name='objet du marché')),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='budget minimal')),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='budget maximal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marché',
                'verbose_name_plural': 'Marchés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='titre de la publication')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='URL source du PDF')),
                ('numero_revue', models.CharField(blank=True, max_length=50, null=True, verbose_name='numéro de la revue')),
                ('date_publication', models.DateField(verbose_name='date de publication')),
                ('fichier_pdf', models.FileField(upload_to=backend.models.publication_upload_path, verbose_name='fichier PDF')),
                ('status', models.CharField(choices=[('DOWNLOADED', 'Téléchargé'), ('PROCESSING', 'Traitement en cours'), ('COMPLETED', 'Traité avec succès'), ('ERROR', 'Erreur de traitement')], default='DOWNLOADED', max_length=20, verbose_name='statut du traitement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='TypeProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True, verbose_name='libellé')),
            ],
            options={
                'verbose_name': 'Type de Procédure',
                'verbose_name_plural': 'Types de Procédures',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='AppelOffre',
            fields=[
                ('marche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='appel_offre', serialize=False, to='backend.marche', verbose_name='marché associé')),
                ('date_depot', models.DateTimeField(blank=True, null=True, verbose_name='date et heure limite de dépôt')),
                ('reference_dossier', models.CharField(blank=True, max_length=255, null=True, verbose_name='référence du dossier')),
                ('lieu_depot', models.TextField(blank=True, null=True, verbose_name='lieu de dépôt des offres')),
                ('cautionnement', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='montant du cautionnement')),
                ('duree_validite_offres', models.CharField(blank=True, max_length=255, null=True, verbose_name='durée de validité des offres')),
            ],
            options={
                'verbose_name': "Appel d'Offre",
                'verbose_name_plural': "Appels d'Offres",
            },
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('marche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='resultat', serialize=False, to='backend.marche', verbose_name='marché associé')),
                ('date_attribution', models.DateField(blank=True, null=True, verbose_name="date d'attribution (délibération)")),
                ('reference_decision', models.CharField(blank=True, max_length=255, null=True, verbose_name='référence de la décision')),
                ('nombre_offres_recues', models.PositiveIntegerField(blank=True, null=True, verbose_name="nombre d'offres reçues")),
                ('delai_execution', models.CharField(blank=True, max_length=255, null=True, verbose_name="délai d'exécution")),
            ],
            options={
                'verbose_name': "Résultat d'attribution",
                'verbose_name_plural': "Résultats d'attributions",
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(blank=True, max_length=50, null=True, verbose_name='numéro du lot')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description du lot')),
                ('montant_propose', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='montant proposé/attribué')),
                ('statut', models.CharField(blank=True, choices=[('RETENU', 'Retenu'), ('NON_CONFORME', 'Non conforme'), ('ANORMALEMENT_BASSE', 'Anormalement basse'), ('REJETE', 'Rejeté'), ('AUTRE', 'Autre')], max_length=50, null=True, verbose_name="statut de l'offre")),
                ('rang', models.CharField(blank=True, max_length=50, null=True, verbose_name='rang')),
                ('motif', models.TextField(blank=True, null=True, verbose_name='motif du statut (si non retenu)')),
                ('nom_entreprise_texte', models.CharField(help_text="Nom de l'entreprise tel qu'extrait du document, même si elle n'est pas dans notre base de données.", max_length=255, verbose_name="nom de l'entreprise (texte brut)")),
                ('entreprise_concernee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participations_lots', to='entreprise.entreprise', verbose_name='entreprise concernée')),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='backend.marche', verbose_name='marché parent')),
            ],
            options={
                'verbose_name': 'Lot / Participation',
                'verbose_name_plural': 'Lots / Participations',
                'ordering': ['marche', 'numero_lot', 'rang'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('DOMAINE', 'Notification par domaine'), ('ENTREPRISE_SPECIFIQUE', 'Notification entreprise spécifique')], max_length=25)),
                ('lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('domaine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='entreprise.domaine', verbose_name='domaine concerné')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='entreprise.entreprise', verbose_name='entreprise concernée')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.lot')),
                ('marche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.marche')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='marche',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marches', to='backend.publication', verbose_name='publication source'),
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(max_length=50)),
                ('date_alerte', models.DateTimeField()),
                ('contenu_alerte', models.TextField()),
                ('canal_alerte', models.CharField(max_length=30)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='entreprise.entreprise')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='backend.publication')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'db_table': 'alerte',
            },
        ),
        migrations.CreateModel(
            name='PublicationDomaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.domaine')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.publication')),
            ],
        ),
        migrations.AddField(
            model_name='marche',
            name='type_procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.typeprocedure', verbose_name='type de procédure'),
        ),
    ]
