# Generated by Django 5.2.1 on 2025-05-09 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('objet', models.CharField(max_length=255)),
                ('autorite_contractante', models.CharField(max_length=255)),
                ('montant_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('devise', models.CharField(default='XOF', max_length=10)),
                ('date_publication', models.DateField()),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('lieu_execution', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=100)),
                ('date_publication', models.DateField()),
                ('source', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppelOffre',
            fields=[
                ('marche_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.marche')),
                ('date_ouverture_plis', models.DateField(blank=True, null=True)),
                ('conditions_participation', models.TextField(blank=True, null=True)),
                ('mode_passation', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('backend.marche',),
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lue', models.BooleanField(default=False)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise')),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.marche')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(max_length=50)),
                ('intitule', models.CharField(max_length=255)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.marche')),
            ],
        ),
        migrations.AddField(
            model_name='marche',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.publication'),
        ),
        migrations.CreateModel(
            name='PublicationDomaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.domaine')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.publication')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='domaines',
            field=models.ManyToManyField(through='backend.PublicationDomaine', to='entreprise.domaine'),
        ),
        migrations.AddField(
            model_name='marche',
            name='type_procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.typeprocedure'),
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('marche_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.marche')),
                ('montant_attribue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date_attribution', models.DateField(blank=True, null=True)),
                ('entreprise_attributaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.entreprise')),
            ],
            bases=('backend.marche',),
        ),
    ]
