# Generated by Django 5.2.1 on 2025-05-23 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministere', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('objet', models.TextField()),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=100)),
                ('date_publication', models.DateField()),
                ('source', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('type_publicaton', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppelOffre',
            fields=[
                ('marche_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.marche')),
                ('dateDepot', models.DateField(blank=True, null=True)),
                ('referenceDossier', models.CharField(blank=True, max_length=255, null=True)),
                ('lieuDepot', models.TextField(blank=True, null=True)),
                ('conditionsParticipation', models.TextField(blank=True, null=True)),
                ('criteresSelection', models.TextField(blank=True, null=True)),
                ('cautionnement', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dureeValiditeOffres', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': "Appel d'Offre",
                'verbose_name_plural': "Appels d'Offres",
            },
            bases=('backend.marche',),
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='backend.marche')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'db_table': 'lot',
            },
        ),
        migrations.AddField(
            model_name='marche',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.publication'),
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(max_length=50)),
                ('date_alerte', models.DateTimeField()),
                ('contenu_alerte', models.TextField()),
                ('canal_alerte', models.CharField(max_length=30)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='entreprise.entreprise')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='backend.publication')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'db_table': 'alerte',
            },
        ),
        migrations.CreateModel(
            name='PublicationDomaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.domaine')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.publication')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='domaines',
            field=models.ManyToManyField(through='backend.PublicationDomaine', to='entreprise.domaine'),
        ),
        migrations.AddField(
            model_name='marche',
            name='type_procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.typeprocedure'),
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('marche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.marche')),
                ('date_attribution', models.DateField(blank=True, null=True)),
                ('montant_attribue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('reference_decision', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_offres_recues', models.IntegerField(blank=True, null=True)),
                ('delai_execution', models.CharField(blank=True, max_length=255, null=True)),
                ('motif_rejet_autres_offres', models.TextField(blank=True, null=True)),
                ('entreprise_attributaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entreprise.entreprise')),
            ],
            options={
                'verbose_name': "Résultat d'attribution",
                'verbose_name_plural': "Résultats d'attribution",
                'db_table': 'resultat',
            },
        ),
    ]
