# Generated by Django 5.2.1 on 2025-05-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='type_publicaton',
            new_name='type_publication',
        ),
    ]
