# Generated by Django 5.2.1 on 2025-07-19 12:58

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="activation_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="activation_token_created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
