# Generated by Django 5.2.1 on 2025-07-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_utilisateur_active_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
